# Generated by Django 4.0.5 on 2022-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/examples/'),
        ),
    ]
